name: Update Calendar

on:
  schedule:
    - cron: '0 3 * * *' # Se ejecuta a las 00:00 AM de Argentina (GMT-3)
  workflow_dispatch:   # Permite ejecutarlo manualmente desde el botón

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # IMPORTANTE: Permiso de escritura habilitado
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run calendar script
        run: python update_calendar.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "📅 Calendario actualizado $(date +'%Y-%m-%d')" || exit 0
          git push